/**
 * @file   const.hh
 * @author Vincent Boucheny <mankalas@gmail.com>
 * @date   Sun Nov  6 19:33:26 2011
 *
 * @brief  Declaration of constants, shared by the view and the controller.
 */

#define STATUE "Statue"
#define THEATER "Theater"
#define COLLEGE "College"
#define MONUMENT "Monument"
#define GRANARY "Granary"
#define WEAVER "Weaver"
#define CATHEDRAL "Cathedral"
#define GOLD_MINE "Gold mine"
#define NEUTRAL_QUARRY "Neutral quarry"
#define WOOD_QUARRY "Wood quarry"
#define WORKSHOP "Workshop"
#define NEUTRAL_FARM "Neutral farm"
#define WOOD_FOOD_FARM "Wood/food farm"
#define WOOD_CLOTH_FARM "Wood/cloth farm"
#define STONE_FARM "Stone farm"
#define FOREST "Forest"
#define NEUTRAL_FOREST "Forest"
#define PARK "Park"
#define NEUTRAL_SAWMILL "Neutral sawmill"
#define WOOD_SAWMILL "Wood sawmill"
#define RESIDENCE "Residence"
#define LIBRARY "Library"
#define HOTEL "Hotel"
#define CHURCH "Church"
#define FIXED_PEDDLER "Fixed peddler"
#define WOOD_PEDDLER "Wood peddler"
#define JEWELLER "Jeweller"
#define TAILOR "Tailor"
#define ALCHEMIST "Alchemist"
#define BANK "Bank"
#define TRADING_POST "Trading post"
#define NEUTRAL_CARPENTER "Neutral carpenter"
#define FIXED_CARPENTER "Fixed carpenter"
#define LAWYER "Lawyer"
#define ARCHITECT "Architect"
#define MASON "Mason"
#define NEUTRAL_MARKETPLACE "Neutral marketplace"
#define WOOD_MARKETPLACE "Wood marketplace"
#define CASTLE "Castle"
#define BRIDGE "Bridge"
#define GATE "Gate"
#define MERCHANT_GUILD "Merchant guild"
#define JOUST_FIELD "Joust field"
#define STABLES "Stables"
#define INN "Inn"
#define FARM_CLOTH "Farm cloth"
#define FARM_FOOD "Farm food"
#define FARM_STONE "Farm stone"

#define foreach BOOST_FOREACH
